# Generated by Django 5.2.7 on 2025-11-11 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="书名")),
                ("author", models.CharField(max_length=100, verbose_name="作者")),
                ("publisher", models.CharField(max_length=100, verbose_name="出版社")),
                (
                    "isbn",
                    models.CharField(max_length=20, unique=True, verbose_name="ISBN"),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, verbose_name="库存数量"),
                ),
                ("publication_date", models.DateField(verbose_name="出版日期")),
            ],
        ),
        migrations.CreateModel(
            name="BorrowRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrower_name",
                    models.CharField(max_length=50, verbose_name="借阅人姓名"),
                ),
                (
                    "borrow_date",
                    models.DateField(auto_now_add=True, verbose_name="借阅日期"),
                ),
                ("due_date", models.DateField(verbose_name="应还日期")),
                (
                    "return_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="实际归还日期"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("borrowed", "借出中"), ("returned", "已归还")],
                        default="borrowed",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                        verbose_name="所借图书",
                    ),
                ),
            ],
        ),
    ]
