# Generated by Django 5.2.7 on 2025-11-12 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_purchaserecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisposalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="淘汰数量")),
                (
                    "disposal_date",
                    models.DateField(auto_now_add=True, verbose_name="淘汰日期"),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="淘汰原因"),
                ),
                (
                    "operator_name",
                    models.CharField(
                        default="admin", max_length=50, verbose_name="操作员"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                        verbose_name="淘汰图书",
                    ),
                ),
            ],
        ),
    ]
