# Generated by Django 5.2.7 on 2025-11-12 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="采购数量")),
                (
                    "purchase_date",
                    models.DateField(auto_now_add=True, verbose_name="采购日期"),
                ),
                (
                    "operator_name",
                    models.CharField(
                        default="admin", max_length=50, verbose_name="操作员"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                        verbose_name="采购图书",
                    ),
                ),
            ],
        ),
    ]
